AWS_ACCESS_KEY = ""
AWS_SECRET_KEY = ""

METACULUS_KEY = ""
MANIFOLD_KEY = ""
POLYMARKET_KEY = ""
CRYPTO_PRIVATE_KEY = ""
EMAIL = ""
GJOPEN_CSET_PASSWORD = ""


NEWSCASTCHER_KEY = ""

OPENAI_KEY = ""
ANTHROPIC_KEY = ""
TOGETHER_KEY = ""
GOOGLE_AI_KEY = ""
HF_ACCESS_TOKEN = ""

keys = {
    "AWS_ACCESS_KEY": AWS_ACCESS_KEY,
    "AWS_SECRET_KEY": AWS_SECRET_KEY,

    "METACULUS_KEY": METACULUS_KEY,
    "MANIFOLD_KEY": MANIFOLD_KEY,
    "POLYMARKET_KEY": POLYMARKET_KEY,
    "CRYPTO_PRIVATE_KEY": CRYPTO_PRIVATE_KEY,
    "EMAIL": EMAIL,
    "GJOPEN_CSET_PASSWORD": GJOPEN_CSET_PASSWORD,

    "NEWSCASTCHER_KEY": NEWSCASTCHER_KEY,

    "OPENAI_KEY": OPENAI_KEY,
    "ANTHROPIC_KEY": ANTHROPIC_KEY,
    "TOGETHER_KEY": TOGETHER_KEY,
    "GOOGLE_AI_KEY": GOOGLE_AI_KEY,
    "HF_ACCESS_TOKEN": HF_ACCESS_TOKEN,
}
